[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bank = "DscUGZtcgGvJ1GX4uTium9YFEd5EyXkNueP2ty9Mwm3X"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
